//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SQLyog.rc
//
#define IDI_MAIN                        1
#define IDC_DIAG_OPTIMIZE               3
#define IDC_EXCELDEFAULT                3
#define IDC_ADD                         3
#define IDC_UP                          4
#define IDC_MOVEDOWN                    4
#define IDCURRDATE                      5
#define ID_SELECTALL                    6
#define IDC_DOWN                        6
#define IDC_UNSELALL2                   10
#define IDC_DIAG_REPAIR                 10
#define IDC_DIAG_ANALYZE                11
#define IDCONTINUE                      11
#define IDC_MOVEUP                      12
#define ID_UNSELECT                     13
#define IDC_SELALL2                     17
#define IDC_UNSELECTALL                 18
#define IDC_DIAG_CHECK                  19
#define IDR_ACCELERATOR                 101
#define IDR_MAINMENU                    104
#define IDD_EXPORTDATA                  166
#define IDD_ABOUTDIALOG                 168
#define IDI_QUERYMESSAGE                169
#define IDI_QUERYRECORD                 170
#define IDI_COPY                        171
#define IDI_CUT                         172
#define IDI_TEMPLATE                    173
#define IDI_OPEN                        174
#define IDI_NEWQUERY                    175
#define IDI_PASTE                       176
#define IDI_SAVE                        177
#define IDI_EXECUTE                     178
#define IDI_REFRESH                     180
#define IDI_QUERY                       190
#define IDI_SMALL                       191
#define IDD_KEYSHORT                    192
#define IDR_TMAKERDROP                  210
#define IDR_QUERYLISTMENU               212
#define IDD_TABLEDIAG                   213
#define IDD_USERMANAGER                 219
#define IDD_FLUSH                       234
#define IDD_TEMPLATE                    235
#define IDR_TEDITORDROP                 236
#define IDD_SHOWVALUE                   242
#define IDD_SCHEMA                      243
#define IDR_SHOWMORE                    253
#define IDR_PROCESS                     254
#define IDD_COPYTABLE                   255
#define IDI_COPYTABLE                   283
#define IDI_EXPORTDATA                  285
#define IDI_FLUSH                       286
#define IDI_KEYSHORT                    287
#define IDI_SCHEMA                      288
#define IDI_TABLEDIAG                   289
#define IDI_IMPORTDATA                  291
#define IDI_FIND                        295
#define IDI_HELP                        298
#define IDD_IMPORTXML                   301
#define IDI_REDOSM                      341
#define IDI_UNDOSM                      342
#define IDI_CHECK                       348
#define IDI_HISTORY                     352
#define IDI_TABLEINDEX                  353
#define IDR_QUERYINFOMENU               354
#define IDD_DBMAKER                     363
#define IDD_INDEXCOLUMNS                369
#define IDD_INSERTUPDATEBLOB            378
#define IDD_IMPORTBATCH                 379
#define IDDONE                          379
#define IDD_ESCAPECHAR                  380
#define IDD_IMPORTCSV                   382
#define IDD_BACKUP                      383
#define IDD_RESTORE                     385
#define IDD_SHOWINFO                    386
#define IDI_SORTASC                     389
#define IDI_SORTDSC                     390
#define IDD_EXPORTRESULTSET             395
#define IDI_DIFFTOOL                    408
#define IDB_BLUE                        418
#define IDB_GREEN                       420
#define IDD_COPYDATABASE                422
#define IDB_BANNER                      423
#define IDB_WATERMARK                   424
#define IDB_DBICON                      439
#define IDB_ARROW                       440
#define IDR_OTHEROPTION                 442
#define IDD_CONNECTIONNAME              447
#define IDD_NEWFOREIGN                  453
#define IDI_ODBC                        460
#define IDI_PROCESS                     464
#define IDI_INSERT                      466
#define IDI_ALTERTABLE                  469
#define IDR_SHOW                        470
#define IDR_USERMANAGER                 471
#define IDI_COPYDATABASE                472
#define IDD_EXPORTXMLHTML               476
#define IDI_XMLHTML                     477
#define IDR_XMLHTML                     478
#define IDD_SQLWHERE                    500
#define IDB_DSYNC1                      502
#define IDB_DSYNC2                      506
#define IDI_USERS                       523
#define IDD_JOBMAN                      528
#define IDI_EXECUTEFORUPD               537
#define IDI_EXECUTEALL                  538
#define IDI_COLUMN                      540
#define IDI_INDEX                       541
#define IDI_TABLE                       544
#define IDI_DATABASE                    545
#define IDI_SERVER                      546
#define IDI_DROPTABLE                   552
#define IDI_DROPCOLUMN                  553
#define IDI_MANINDEX                    556
#define IDI_TILE                        560
#define IDI_NEWDATABASE                 570
#define IDI_REPLACE                     575
#define IDI_EXECBATCH                   577
#define IDI_REORDER                     579
#define IDI_MANREL                      582
#define IDI_DISCON                      584
#define IDI_DISCONALL                   585
#define IDI_RESTORE                     588
#define IDI_BACKUP                      590
#define IDI_CREATETABLE                 591
#define IDI_CONNECT                     596
#define IDI_CASCADE                     598
#define IDD_JOBINTERIOR5                609
#define IDB_JOBBIG                      615
#define IDB_JOBSMALL                    616
#define IDI_JOBMANAGER                  617
#define IDI_NOTIFICATION                618
#define IDI_EDITUSER                    619
#define IDI_ADDUSER                     620
#define IDI_CSV                         622
#define IDI_EMPTYDB                     624
#define IDI_RENAME                      626
#define IDI_TABLEPROP                   627
#define IDI_TRUNCDB                     628
#define IDI_VIEWDATA                    629
#define IDI_DBSYNC                      643
#define IDI_PREF                        644
#define IDI_REORDERCOL                  645
#define IDI_EMPTYTABLE                  646
#define IDI_DROPDB                      647
#define IDI_MYSQL                       650
#define IDI_TUNNEL                      652
#define IDI_SERVERGROUP                 653
#define IDB_CONNECTION                  662
#define IDD_PROXY                       663
#define IDB_SCHDBIG                     666
#define IDB_SCHDSMALL                   669
#define IDI_STOP                        671
#define IDR_FILTER                      673
#define IDI_EXPORTRESULTCSV             675
#define IDR_TABLEDATAMENU               676
#define IDI_EXPORTSELCSV                678
#define IDI_EXPORTSELCELLCSV            680
#define IDI_RESULTCANCEL                686
#define IDI_RESULTDELETE                687
#define IDI_RESULTINSERT                688
#define IDI_RESULTSAVE                  689
#define IDI_SCHDEXPORT                  690
#define IDI_EMAILMANAGER                691
#define IDD_SHOWWARNING                 723
#define IDD_SHOWIMPORTERR               724
#define IDB_SCHDODBC                    730
#define IDD_PREF2                       731
#define IDI_VIEW                        747
#define IDI_CREATEVIEW                  748
#define IDI_ALTERVIEW                   749
#define IDI_DROPVIEW                    750
#define IDI_PROCEDURE                   751
#define IDI_CREATEPROCEDURE             752
#define IDI_ALTERPROCEDURE              753
#define IDI_DROPPROCEDURE               754
#define IDI_CREATETRIGGER               756
#define IDI_ALTERTRIGGER                757
#define IDI_DROPTRIGGER                 758
#define IDI_CREATEFUNCTION              760
#define IDI_ALTERFUNCTION               761
#define IDI_DROPFUNCTION                762
#define IDR_MENUFAV                     776
#define IDI_FAVORITES                   784
#define IDI_ORGANIZEFAV                 785
#define IDI_ADDTOFAV                    786
#define IDI_SQL                         787
#define IDD_PREF3                       788
#define IDR_TABMENU                     791
#define IDR_QBGRIDMENU                  796
#define IDR_QBLINEOPTION                797
#define IDI_QUERYBUILDER                797
#define IDR_EDITORCONTEXT               798
#define IDI_SCHEMADESIGNER              802
#define IDD_CREATEDB                    802
#define IDD_MYSQL_ERROR                 803
#define IDD_REGISTERSPLASH              804
#define IDI_PKEY                        810
#define IDI_CLOSETABLE                  812
#define IDI_SDTABLEVIEW                 813
#define IDI_EXPORTASIMG                 815
#define IDI_SDPRINT                     816
#define IDI_COMMIT                      817
#define IDI_ROLLBACK                    818
#define IDI_START_TRANSACTION           819
#define IDI_ADDTABLES                   820
#define IDI_ALTERDB                     821
#define IDI_PREVIOUS                    824
#define IDI_NEXT                        825
#define IDI_QAALERT                     831
#define IDI_QADONTALERT                 832
#define IDI_FORMATQUERY                 833
#define IDI_ABOUTICO                    836
#define IDI_EXITICO                     837
#define IDI_EVENT                       838
#define IDI_REFRESHCANVAS               839
#define IDR_TABLESMENU                  840
#define IDI_COMMIT_16                   841
#define IDI_ROLLBACK_16                 842
#define IDI_START_TRANSACTION_16        843
#define IDI_SDZOOMIN                    845
#define IDI_SDZOOMOUT                   846
#define IDI_ALTEREVENT                  847
#define IDI_DROPEVENT                   848
#define IDI_RENAMEEVENT                 849
#define IDI_LINEICON                    850
#define IDI_CHECKICON                   851
#define IDI_UNCHECKICON                 852
#define IDI_ENTMENU                     856
#define IDD_GETSQLYOGENTERPRISE         857
#define IDD_UPGRADECHK                  858
#define IDD_PREFOTHERS                  859
#define IDD_PREFGENERAL                 860
#define IDI_RESETFILTER                 864
#define IDI_CLOSETAB                    865
#define IDI_FAVREFRESH                  866
#define IDI_INDEXCREATE                 867
#define IDI_INDEXEDIT                   868
#define IDI_INDEXDROP                   869
#define IDI_RENAMETRIGGER               870
#define IDI_RENAMEVIEW                  871
#define IDI_EXPORTVIEW                  872
#define IDI_COPYQUERYTOCLIP             873
#define IDI_COPYQUERYTOCURTAB           874
#define IDI_COPYQUERYTONEWTAB           875
#define IDI_FOLDER                      876
#define IDI_CREATEEVENT                 878
#define IDI_TRIGGER                     879
#define IDI_FUNCTION                    880
#define IDI_CONNECT_16                  882
#define IDI_SAVEAS                      884
#define IDI_COPYDATABASE_16             886
#define IDI_DBSYNC_16                   887
#define IDI_EXECUTEALL_16               888
#define IDI_EXECUTE_16                  889
#define IDI_EXECUTEFORUPD_16            890
#define IDI_EXPORTDATA_16               891
#define IDI_QUERYBUILDER_16             892
#define IDI_QUERY_16                    893
#define IDI_SCHEMADESIGNER_16           894
#define IDI_SCHDEXPORT_16               895
#define IDI_NOTIFICATION_16             896
#define IDI_REFRESH_16                  897
#define IDI_MANREL_16                   898
#define IDI_MANINDEX_16                 899
#define IDI_EXECBATCH_16                900
#define IDI_XMLHTML_16                  901
#define IDI_ODBC_16                     902
#define IDI_DIFFTOOL_16                 903
#define IDI_DATASEARCH                  904
#define IDI_PRIMARYKEY                  905
#define IDR_INFOTABMENU                 906
#define IDI_OPENINNEWTAB                908
#define IDI_USERMANAGER                 909
#define IDD_QUERYPREVIEW                909
#define IDD_ENUMSETVALUES               911
#define IDI_CONNCOLOR                   911
#define IDI_RENAMEUSER                  912
#define IDR_FIXTABMENU                  914
#define IDD_STARTDLG                    916
#define IDB_COMSPLASH                   918
#define IDD_CUSTOMFILTER                919
#define IDI_USER_ADD                    919
#define IDI_USER_WRITE                  920
#define IDI_USER_16                     921
#define IDR_GRIDVIEWMENU                921
#define IDI_USER_GLOBALPRIV             922
#define IDI_USER_OBJECTPRIV             923
#define IDI_DATAVIEWTYPE                924
#define IDD_LANGUAGE                    925
#define IDR_README2                     928
#define IDR_README                      928
#define IDD_FKDIALOG                    929
#define IDR_TABPLUSMENU                 930
#define IDR_CONNTABPLUSMENU             932
#define IDD_DIALOG1                     933
#define IDD_DATETIME                    933
#define IDD_DLGCOLUMNS                  934
#define IDD_DIALOG2                     934
#define IDD_CONNECTION_DETAILS_MANAGER  934
#define IDI_ICON2                       937
#define IDI_DUPLICATEROW                937
#define IDI_CALENDAR                    940
#define IDI_ICON3                       941
#define IDI_ICON4                       942
#define IDD_SELDB                       945
#define IDD_SEARCHFILTER                945
#define IDI_ICON5                       948
#define IDI_TABLEOPTIONS                948
#define IDI_ICON6                       949
#define IDI_TABPREVIEW                  949
#define IDI_CIRCLE8                     950
#define IDI_CIRCLE1                     951
#define IDI_CIRCLE2                     952
#define IDI_ICON9                       953
#define IDI_CIRCLE3                     953
#define IDI_CIRCLE4                     954
#define IDI_CIRCLE5                     955
#define IDI_CIRCLE6                     956
#define IDI_CIRCLE7                     957
#define IDD_DIALOG3                     958
#define IDD_CREATEALTER                 958
#define IDI_FILTER                      958
#define IDR_PREVIEWMENU                 961
#define IDI_TABLEEXPORT                 962
#define IDR_THEME_TWILIGHT              963
#define IDR_THEME_FLAT                  964
#define IDI_VIEWTYPE                    965
#define IDI_TABLEREFRESH                966
#define IDI_DATAGRID                    967
#define IDI_FORMICON                    968
#define IDI_TEXTVIEW                    970
#define IDB_TWILIGHT_THEME_BITMAP       984
#define IDD_CONNECTION_IMPORT_MANAGER   987
#define IDD_CONNECTION_IMPORT_CONFLICT  989
#define IDR_MENU1                       990
#define IDR_MESSAGETAB_MENU             990
#define IDR_MESSAGETABMENU              991
#define IDI_REMOVE_FILTER               994
#define IDI_REMOVE_DB_FILTER            995
#define IDI_OVERLAYFILTER               997
#define IDR_CONNTABPLUSMENU1            998
#define IDB_PNG1                        1004
#define IDC_DLGCONNECT_USER             1005
#define IDI_ICON1                       1005
#define IDI_VDD                         1005
#define IDC_DLGCONNECT_PASSWORD         1006
#define IDC_DLGCONNECT_PORT             1007
#define IDC_DLGCONNECT_HOST             1008
#define IDC_DLGCONNECT_DATABASE         1009
#define IDC_SSHPORT                     1010
#define IDC_SSHPORT2                    1015
#define IDB_PNG2                        1015
#define IDD_CONNECTIONLIST              1016
#define IDD_RESTORE_STATUS              1017
#define IDC_FORMATTERPREVIEW            1024
#define IDC_COLLIST                     1037
#define IDC_TEMPLIST                    1037
#define IDC_TABLELIST                   1037
#define IDC_JOBS                        1037
#define IDC_COLUMNLIST                  1037
#define IDC_CSVFIELDS                   1038
#define IDC_DBNAME                      1039
#define IDC_TABLENAME                   1040
#define IDC_SQLGROUP                    1040
#define IDC_SAMPLE                      1041
#define IDC_COMMENT                     1041
#define IDC_IGNORENUM                   1041
#define IDC_INFO                        1041
#define IDC_URL                         1041
#define IDC_PROXY                       1041
#define IDC_SQLFILE                     1041
#define IDC_DBEDIT                      1041
#define IDC_AUTOCOMPLETETAGSDIR         1041
#define IDC_INDENTATION                 1041
#define IDC_VALUE                       1041
#define IDC_MAXQUERIES                  1041
#define IDC_FESCAPE                     1042
#define IDC_DESC                        1042
#define IDC_HIGHLIMIT                   1042
#define IDC_PROXYPORT                   1042
#define IDC_HTTPTIME                    1043
#define IDC_LESCAPE                     1043
#define IDC_PROXYUSERNAME               1043
#define IDC_FENCLOSED                   1044
#define IDC_PROXYPWD                    1044
#define IDC_CHALLENGEUSER               1045
#define IDC_CHALLENGEPWD                1046
#define IDC_REFRESH                     1047
#define IDC_IMPORT                      1047
#define IDC_EDITCONN                    1047
#define IDC_KEYINDEX                    1047
#define IDC_SQLCHANGE                   1047
#define IDC_SHOWWARNINGS                1047
#define IDC_OPEN                        1047
#define IDC_SAVE_BUTTON                 1047
#define IDC_BUYNOW                      1047
#define IDC_FORMATTERRESTOREALL         1047
#define IDC_SUMMARY                     1047
#define IDC_UM_HELP                     1047
#define IDC_SELECTALL                   1048
#define IDC_DROP                        1048
#define IDC_SAVETOFILE                  1048
#define IDC_SAVE                        1048
#define IDC_REFINDEX                    1048
#define IDC_DATACHANGE                  1048
#define IDC_DIRSEL                      1048
#define IDC_CHANGE                      1049
#define IDC_TUNNELHELP                  1049
#define IDC_STRINGCOLOR                 1049
#define IDC_DIAG_CHKUNCHK               1050
#define IDC_DESELECTALL                 1050
#define IDC_SSHHELP                     1050
#define IDC_FUNCTIONCOLOR               1050
#define IDC_REMOVE                      1050
#define IDC_TEXT                        1051
#define IDC_SSHUSER                     1051
#define IDC_KEYWORDCOLOR                1051
#define IDC_FKNAME                      1051
#define IDC_ROW_LIMIT                   1051
#define IDC_FILTER_CUSTOM_STRING        1051
#define IDC_MAXUPDATE                   1051
#define IDC_FILTER_CUSTOM_STRING1       1051
#define IDC_FILTER_VALUE                1051
#define IDC_SSHPWD                      1052
#define IDC_NORMALCOLOR                 1052
#define IDC_PASSWORD_CONFIRM            1052
#define IDC_FILTER_CUSTOM_STRING2       1052
#define IDC_ALLFIELDS                   1053
#define IDC_LOWPRIORITY                 1053
#define IDC_ESCAPED                     1053
#define IDC_SSH                         1053
#define IDC_USECHALLENGE                1053
#define IDC_COMMENTCOLOR                1053
#define IDC_DEF_BULK_SIZE               1053
#define IDC_REFRESHTABLEDATA            1053
#define IDC_SINGLE_TRANSACTION          1053
#define IDC_PRIVILEGEDCHECK             1053
#define IDC_FILTER_CUSTOM_STRING3       1053
#define IDC_CONCURRENT                  1054
#define IDC_LINESTERM                   1054
#define IDC_ALLINDEX                    1054
#define IDC_SSHHOST                     1054
#define IDD_ORGFAVORITES                1054
#define IDC_BLOBCHANGE                  1054
#define IDC_HTTPENCODEOPTION            1054
#define IDC_FILTER_CUSTOM_STRING4       1054
#define IDD_MOVETOFOLDER                1055
#define IDC_DIAG_QUICKREPAIR            1055
#define IDC_FIELDSTERMINATED            1055
#define IDC_TRIGGERS                    1055
#define IDC_HISTORYCHANGE               1055
#define IDC_FILTER_CUSTOM_STRING5       1055
#define IDD_ADDFAVORITES                1056
#define IDC_FIELDSENCLOSED              1056
#define IDC_BLOB                        1056
#define IDC_MAXCONN                     1056
#define IDD_GETFOLDERNAME               1057
#define IDC_SSH2                        1057
#define IDC_COLUMNS                     1057
#define IDC_DECIMAL                     1057
#define IDC_SSHHELP2                    1058
#define IDC_SETMAXROW                   1058
#define IDD_TEXTENTRYDIALOG             1058
#define IDC_REPLACE                     1059
#define IDC_SSHUSER2                    1059
#define IDC_IGNORE                      1060
#define IDC_DIAG_EXTENDEDREPAIR         1060
#define IDC_SSHPWD2                     1060
#define IDC_OPENTABLES                  1060
#define IDD_CONNECT                     1060
#define IDC_IGNORELINES                 1061
#define IDC_SSHHOST2                    1061
#define IDC_DIAG_USEFRMREPAIR           1061
#define IDC_OPENTABLES2                 1061
#define IDC_CONRESTORE                  1061
#define IDC_DIAG_USELOCALREPAIR         1062
#define IDC_TAB                         1062
#define IDD_PREFFORMATTER               1062
#define IDC_MAXSIMCONN                  1062
#define IDC_DIAG_OPTIMIZELOCAL          1063
#define IDD_EMPTYDB                     1063
#define IDC_DIAG_ANALYZELOCAL           1064
#define IDC_ENABLEUPGRADE               1064
#define IDD_GETSQLYOGULTIMATE           1064
#define IDD_OBCOLOR                     1065
#define IDC_TRANSACTION                 1067
#define IDC_EXPORTFILENAME              1081
#define IDC_PROGRESS                    1082
#define IDC_CHK_USEDBNAME               1083
#define IDC_CHK_DROPOBJECT              1084
#define IDC_CHK_DATA                    1085
#define IDC_CHK_STRUCTURE               1086
#define IDC_MESSAGE                     1087
#define IDC_CHK_DATAONLY                1087
#define IDC_EXPFILESELECT               1088
#define IDC_CHK_LOCKAROUNDINSERT        1089
#define IDC_CHK_LOCKFORREAD             1090
#define IDC_DATAONLY                    1090
#define IDC_CHK_FLUSHLOGS               1091
#define IDC_CHK_CREATEDB                1092
#define IDC_WARNING                     1093
#define IDC_SETUNIQUE                   1093
#define IDC_BULKINSERT                  1094
#define IDC_CHK_DEFINER                 1095
#define IDC_CHK_VERSION                 1096
#define IDC_ONEROW                      1097
#define IDC_NULLREPLACEBY               1098
#define IDC_CHK_HEXBLOB                 1098
#define IDC_OBFONT                      1099
#define IDC_NULLCHAR                    1099
#define IDC_COMBO                       1101
#define IDC_CHARSETCOMBO                1101
#define IDC_TABCOLLATION                1101
#define IDC_CONTENTTYPE                 1101
#define IDC_KEYWORDCASE                 1101
#define IDC_ICONSIZE                    1101
#define IDC_COLORCOMBO1                 1101
#define IDC_COLUMN_NAMES                1101
#define IDC_LANGCOMBO                   1101
#define IDC_COLUMN_NAMES1               1101
#define IDC_FILTER_COLUMN               1101
#define IDC_COLUMN_NAMES2               1102
#define IDC_DIAG_DATABASE               1103
#define IDC_COLUMN_NAMES3               1103
#define IDC_DIAG_TABLES                 1104
#define IDC_COLUMN_NAMES4               1104
#define IDC_COLUMN_NAMES5               1105
#define IDC_KEYSHORTS                   1106
#define IDC_HORZ                        1108
#define IDC_FL_LOGS                     1110
#define IDC_FL_HOSTS                    1111
#define IDC_FL_PRIV                     1112
#define IDC_FL_TABLES                   1113
#define IDC_FL_TABLESREAD               1114
#define IDC_FL_STATUS                   1115
#define IDC_MSG                         1116
#define IDC_FLUSH_ALL                   1117
#define IDC_FL_DES                      1118
#define IDC_FL_CACHE                    1119
#define IDC_LINK                        1120
#define IDC_FL_BINLOG                   1120
#define IDC_SSL                         1122
#define IDC_STRUC                       1123
#define IDC_STRUCDATA                   1124
#define IDC_STATIC2                     1125
#define IDC_STATICTITLE                 1126
#define IDC_STATICTITLE2                1127
#define IDC_STATICTITLE3                1128
#define IDC_MAXQUERY_SPIN               1128
#define IDC_MAXUPDATE_SPIN              1129
#define IDC_USERNAME                    1130
#define IDC_HOSTNAME                    1131
#define IDC_PASSWORD                    1132
#define ID_OK                           1133
#define IDC_MINROW                      1134
#define IDC_PRIVLIST                    1135
#define IDC_TABLES                      1136
#define IDC_BOTTOMLINE                  1137
#define IDC_NEW                         1139
#define IDC_DELETE                      1140
#define IDC_EDIT                        1141
#define IDC_NEWUSER                     1144
#define IDC_TOPLINE                     1147
#define IDC_BOTLINE                     1148
#define IDC_CREATE                      1153
#define IDC_TARGETDB                    1160
#define IDC_ROWFORMAT                   1161
#define IDC_AUTOINCR                    1163
#define IDC_CHECKSUM                    1164
#define IDC_DELAYKEY                    1165
#define IDC_MAINTAB                     1168
#define IDC_SETNULL                     1169
#define IDC_NULLCHARDISPLAY             1170
#define IDC_IMAGE                       1172
#define IDC_MESSAGE2                    1173
#define IDC_FIELDLIST                   1174
#define IDC_ESCAPECHAR                  1176
#define IDC_FIXEDLENGTH                 1177
#define IDC_LINESCHAR                   1177
#define IDC_VARIABLE                    1178
#define IDC_FIELDSCHAR                  1178
#define IDC_OPTIONAL                    1179
#define IDC_ENCLOSEDCHAR                1179
#define IDC_ESCAPETITLE                 1180
#define IDC_LINESTITLE                  1181
#define IDC_FIELDSTITLE                 1182
#define IDC_ENCLOSEDTITLE               1183
#define IDC_EXPORTDIRNAME               1184
#define IDC_NULLCHARTITLE               1185
#define IDC_XML                         1189
#define IDC_HTML                        1190
#define IDC_CURDATABASE                 1190
#define IDC_CSV                         1191
#define IDC_EXCEL                       1192
#define IDC_SOURCEDB                    1193
#define IDC_SQL                         1193
#define IDC_CHECKBOX                    1194
#define IDC_SOURCEDB2                   1194
#define IDC_OBCHANGE                    1199
#define IDC_STATIC1                     1200
#define IDC_ADDCOLUMNS                  1201
#define IDC_VERSION                     1202
#define IDC_DEF_QBTAB                   1211
#define IDC_ONDELETE                    1211
#define IDC_COLUMNWIDTH                 1211
#define IDC_TUNNEL                      1211
#define IDC_USEPROXY                    1211
#define IDC_FL_RESOURCE                 1211
#define IDC_UPGRDCHK                    1211
#define IDC_EMPTYDBSELECTALL            1211
#define IDC_HIDECOLUMNS                 1211
#define IDC_SELECTALLCHECK              1211
#define IDC_DEF_SDTAB                   1212
#define IDC_ONUPDATE                    1212
#define IDC_WORDWRAP                    1212
#define IDC_RETAINCOLUMNWIDTH           1212
#define IDC_UPDATEPROMPT                1213
#define IDC_BACKQUOTES                  1214
#define IDC_FOCUSAFTERQUERY             1215
#define IDC_CONFIRMONTABCLOSE           1216
#define IDC_GETTEXTONDBCLICK            1217
#define IDC_BACKQUOTES2                 1218
#define IDC_AUTOCOMPLETE                1219
#define IDC_SERVERDATE                  1219
#define IDC_GETINFOKW                   1219
#define IDC_AUTOCOMPLETEREBUILD         1220
#define IDC_SERVERDATE2                 1220
#define IDC_AUTOCOMPLETESHOWTOOLTIP     1221
#define IDC_QUERY                       1232
#define IDC_ERROR_NUMBER                1233
#define IDC_PARSE                       1234
#define IDC_ERROR_MESSAGE               1234
#define IDC_MYSQLPWDST                  1254
#define IDC_MYSQLPORTST                 1255
#define IDC_DESCSTATIC                  1256
#define IDC_MYSQLDBST                   1257
#define IDC_COLONST                     1258
#define IDC_ONDELCASCADE                1264
#define IDC_ONDELNULL                   1265
#define IDC_ONDELNOACTION               1266
#define IDC_ONDELRESTRICT               1267
#define IDC_ONUPDATECASECADE            1268
#define IDC_ONUPDATENULL                1269
#define IDC_ONUPDATENOACTION            1270
#define IDC_ONUPDATERESTRICT            1271
#define IDC_CHECKOPTION                 1273
#define IDC_REGINFO                     1283
#define IDC_KILL                        1284
#define IDC_EXECUTE                     1292
#define IDC_SQLFONT                     1297
#define IDC_DATAFONT                    1298
#define IDC_STATICURL                   1319
#define IDC_TESTCONN                    1320
#define IDC_CONNTAB                     1321
#define IDC_SSHUSERST                   1324
#define IDC_SSHPWDST                    1325
#define IDC_SSHHOSTST                   1326
#define IDC_SSHPORTST                   1327
#define IDC_TUNNELGRP                   1330
#define IDC_SSHGRP                      1331
#define IDC_MYSQLHOSTST                 1332
#define IDC_MYSQLUSERST                 1333
#define IDC_SSHGRP2                     1337
#define IDC_SSHUSERST2                  1338
#define IDC_SSHPWDST2                   1339
#define IDC_SSHHOSTST2                  1340
#define IDC_SSHPORTST2                  1342
#define IDC_TUNNELST                    1346
#define IDC_APPINFO                     1347
#define IDC_LOGO                        1350
#define IDC_HTTPTIMEST                  1351
#define IDC_HTTPTIMEST2                 1354
#define IDC_SIZESTATIC                  1361
#define IDC_AFTERCOMMA                  1363
#define IDC_KEEPTABS                    1363
#define IDC_CURRENTSQL                  1373
#define IDC_BEFORECOMMA                 1373
#define IDC_INSERTSPACES                1373
#define IDC_PROXYSTATIC                 1374
#define IDC_SQLFROMFILE                 1374
#define IDC_PROXYUSERSTATIC             1375
#define IDC_POWERTOOLSRESTORETAB        1376
#define IDC_OTHERSRESTORETAB            1376
#define IDC_FORMATTERRESTORETAB         1376
#define IDC_HTTPAUTH                    1377
#define IDC_PROXYPORTSTATIC             1378
#define IDC_PROXYPWDSTATIC              1379
#define IDC_CHALLENGEUSERSTATIC         1380
#define IDC_CHALLENGEPWDSTATIC          1381
#define IDC_TREE                        1385
#define IDC_JSON                        1391
#define IDC_STATICIMG                   1398
#define IDC_OPENFILE                    1399
#define IDC_CPY_ASCTRIGGERS             1401
#define IDC_WHERETITLE                  1406
#define IDC_STRINGS                     1408
#define IDC_FUNCTIONS                   1409
#define IDC_KEYWORDS                    1410
#define IDC_NORMAL                      1411
#define IDC_NORMAL2                     1412
#define IDC_CAPTION                     1413
#define IDC_OBTREE                      1423
#define IDC_PREVIEW                     1424
#define IDC_AUTOCOMPLETEHELP            1425
#define IDC_GRPBASIC                    1431
#define IDC_GRP41                       1432
#define IDC_GRP51                       1434
#define IDC_EDITOR                      1436
#define IDC_EDITOR2                     1437
#define IDC_CSVOPTIONS                  1437
#define IDC_EDITOR3                     1438
#define IDC_CSVLINES                    1438
#define IDC_EDITOR4                     1439
#define IDC_EXCELOPTIONS                1439
#define IDC_                            1440
#define IDC_SELFLDS                     1440
#define IDC_EDITOR5                     1440
#define IDC_BLOBFONT                    1441
#define IDC_BLOBTEXT                    1441
#define IDC_HISTORYFONT                 1442
#define IDC_DECIMALTEXT                 1442
#define IDC_STRUCTUREONLY               1444
#define IDC_BOTH                        1445
#define IDC_COMLINK                     1447
#define IDC_TABCHARSET                  1452
#define IDC_COLLATECOMBO                1454
#define IDC_MYSQL_ERROR                 1457
#define IDC_STATIC_QUERY                1458
#define IDC_SWITCHSHORTCUT              1458
#define IDC_STATIC_ERRNO                1459
#define IDC_EXPORT_DBCOMBO              1459
#define IDC_STATIC_ERRMSG               1460
#define IDC_EXPORTTREE                  1460
#define IDC_PRIVOBTREE                  1460
#define IDC_STATIC_MYSQLERROR           1461
#define IDC_TRANSACTIONENABLE           1467
#define IDC_CPY_BULKINSERT              1467
#define IDC_CPY_DEFINER                 1468
#define IDC_POWERTOOLSRESTOREALL        1469
#define IDC_OTHERSRESTOREALL            1469
#define IDC_NOTNOW                      1488
#define IDC_GENRESTOREALL               1494
#define IDC_GENRESTORETAB               1495
#define IDC_EDITORRESTOREALL            1496
#define IDC_EDITORRESTORETAB            1497
#define IDC_FKCHKIMPORT                 1498
#define IDC_PQA                         1499
#define IDC_STACKED                     1501
#define IDC_FUNCTIONCASE                1501
#define IDC_PQAEXPLAIN                  1501
#define IDC_NOTSTACKED                  1502
#define IDC_ACGROUP                     1502
#define IDC_DEFTABGROUP                 1503
#define IDC_TAGDIRGROUP                 1504
#define IDC_OPTIONSGROUP                1505
#define IDC_PQAGROUP                    1506
#define IDC_PTGROUP                     1507
#define IDC_PRWGROUP                    1508
#define IDC_PQAEXPLAINEXT               1508
#define IDC_INDENT                      1509
#define IDC_PQASTATUS                   1509
#define IDC_PQAPROF                     1510
#define IDC_SPACES                      1512
#define IDC_BLOBSIZE                    1513
#define IDC_SIZETEXT                    1514
#define IDC_OBJECTSLIST                 1514
#define IDC_STATICEMPTYDB               1515
#define IDC_QUERYPREVIEW                1517
#define IDC_VALUELIST                   1520
#define IDC_KEYSTATIC                   1522
#define IDC_COMPRESS                    1523
#define IDC_TIMEOUT                     1524
#define IDC_TIMEOUTDEF                  1525
#define IDC_TIMEOUTOPT                  1526
#define IDC_TIMEOUTEDIT                 1527
#define IDC_COMPRESSHELP                1533
#define IDC_TIMEOUTHELP                 1534
#define IDC_TIMESEC                     1535
#define IDC_SHOWWARNING                 1536
#define IDC_HALTEXEC                    1539
#define IDC_GETULT                      1540
#define IDC_ENTFEATURE                  1541
#define IDC_GETENTTEXT                  1542
#define IDC_COLORTXT2                   1544
#define IDC_COLORTXT1                   1545
#define IDC_COLORCOMBO                  1546
#define IDC_HTTPSOCKET                  1548
#define IDC_HTTPSOCKETGRP               1549
#define IDC_COLORSTATIC3                1550
#define IDC_RESUTTABPAGERETAIN          1551
#define IDC_RESUTTABPAGE                1552
#define IDC_CONTEXTHELP                 1556
#define IDC_FILTER_COND                 1557
#define IDC_CONTEXTICON                 1557
#define IDC_FILTER_COND1                1557
#define IDC_HELPZERO                    1558
#define IDC_FILTER_COND2                1558
#define IDC_USERCOMBO                   1559
#define IDC_FILTER_COND3                1559
#define IDC_DELUSER                     1560
#define IDC_FILTER_COND4                1560
#define IDC_FILTER_COND5                1561
#define IDC_SAVE_CHANGES                1563
#define IDC_CANCEL_CHANGES              1564
#define IDC_UM_USER                     1565
#define IDC_MAXCONN_SPIN                1566
#define IDC_MAXSIMCONN_SPIN             1567
#define IDC_MAXQUERY_PROMPT             1568
#define IDC_MAXCONN_PROMPT              1569
#define IDC_MAXUPDATE_PROMPT            1570
#define IDC_USERNAME_PROMPT             1571
#define IDC_HOST_PROMPT                 1572
#define IDC_PASSWORD_PROMPT             1573
#define IDC_PASSWORD2_PROMPT            1574
#define IDC_MAXCONNSIM_PROMPT           1575
#define IDC_PRIV_NOTE                   1576
#define IDC_GRIP                        1577
#define IDC_USEDBNAME                   1578
#define IDC_HTTPSOCKETSTATIC            1579
#define IDC_TEXTFILTERDB                1579
#define IDC_EDITMODE                    1580
#define IDC_HTTPSOCKETPATH              1582
#define IDC_MSQLOPTIONSGRP              1583
#define IDC_MODEGLOBAL                  1584
#define IDC_LIMITROWS                   1587
#define IDC_FIRSTROW                    1588
#define IDC_PREV                        1589
#define IDC_ROWSTART                    1590
#define IDC_ROWS                        1592
#define IDC_ROWCOUNT                    1593
#define IDC_FILTERPROMPT                1594
#define IDC_SEARCHTEXT                  1595
#define IDC_COLUMN_FILTER               1596
#define IDC_REFRESHFK                   1597
#define IDC_NAVGROUP                    1598
#define IDC_SIZEGRIP                    1599
#define IDC_LIST1                       1600
#define IDC_LISTCOLUMNS                 1600
#define IDC_STATIC7                     1600
#define IDC_DIAG_ICON                   1600
#define IDC_MONTHCALENDAR1              1600
#define IDC_CONNECTIONLIST              1600
#define IDC_DATETIMEPICKER1             1601
#define IDC_DIAG_GROUP1                 1601
#define IDC_BUTTON2                     1602
#define IDC_DIAG_GROUP2                 1602
#define IDC_OPENCONNDLG                 1602
#define IDC_DIAG_GROUP3                 1603
#define IDC_DIAG_GROUP4                 1604
#define IDC_COPYDATABASE_ICON           1605
#define IDC_GROUPB                      1606
#define IDC_GROUP2                      1607
#define IDC_STATIC_NOTE                 1608
#define IDC_GROUP3                      1609
#define IDC_GROUP4                      1610
#define IDC_TEXT1                       1611
#define IDC_STATIC_NOTE2                1611
#define IDC_TEXT2                       1612
#define IDC_GROUP6                      1612
#define IDC_STATIC_NOTE3                1612
#define IDC_TEXT3                       1613
#define IDC_TEXT4                       1614
#define IDC_GROUP                       1615
#define IDC_ICON_EXP                    1616
#define IDC_GROUP5                      1616
#define IDC_DATETIMEPICKER2             1618
#define IDC_HORZ2                       1620
#define IDC_HORZBAR2                    1620
#define IDC_HORZBAR3                    1621
#define IDC_HORZBAR1                    1622
#define IDC_HORZBAR4                    1623
#define IDC_STAT_HORZ                   1626
#define IDC_TEMP_STATIC                 1629
#define IDC_TEMP_STATIC1                1630
#define IDC_JOB_HORZ                    1631
#define IDC_JOB_STATIC                  1632
#define IDC_JOB_HORZ2                   1633
#define IDC_ORG_TEXT1                   1634
#define IDC_ORG_HORZ                    1635
#define IDC_ORG_HORZ2                   1636
#define IDC_MONTHCALENDAR3              1639
#define IDC_ADDFAV_GRIP                 1641
#define IDC_ORGFAV_GRIP                 1642
#define IDC_COPYTABLE_GRIP              1643
#define IDC__EXPORTAS_GRIP              1644
#define IDC_TABLEDIAG_GRIP              1645
#define IDC_EXPDAT_GRIP                 1646
#define IDC_COPYDATA_GRIP               1647
#define IDC_BTNUP                       1649
#define IDC_BTNDOWN                     1650
#define IDC_COMBO1                      1651
#define IDC_COLORCOMBO2                 1651
#define IDC_COLORCOMBO3                 1651
#define IDC_THEMECOMBO                  1651
#define IDC_COLORTXT3                   1653
#define IDC_CLONECONN                   1654
#define IDC_KEEPALIVE                   1655
#define IDC_CHECK2                      1657
#define IDC_SELALL_ITEM                 1657
#define IDC_LISTITEM                    1658
#define IDC_DBLIST                      1658
#define IDC_CHECK6                      1664
#define IDC_LONGSTR_SD                  1664
#define IDC_CHKUNCHK                    1664
#define IDC_FILTER_GB                   1666
#define IDC_SELALL_SD                   1667
#define IDC_NUMERIC_SD                  1668
#define IDC_SHORTSTR_SD                 1669
#define IDC_BINARY_SD                   1670
#define IDC_CHECK7                      1671
#define IDC_DATETIME_SD                 1672
#define IDC_GRIP_SD                     1673
#define IDC_BLOB_SD                     1674
#define IDC_ITEM_SEL                    1675
#define IDC_DATATYPE_GB                 1676
#define IDC_SELALL_GB                   1677
#define IDC_HEADING                     1679
#define IDC_INDEXGRIP                   1680
#define IDC_TABLEGRIP                   1681
#define IDC_TAB1                        1682
#define IDC_TREE1                       1683
#define IDC_TREE2                       1684
#define IDC_BUTTONFOREGROUNDPREF        1685
#define IDC_BUTTONFOREGROUNDPREF2       1686
#define IDC_BUTTONBACKGROUNDPREF2       1686
#define IDC_CONNECTION_FILE             1687
#define IDC_EDITPREFDEMO                1688
#define IDC_RICHEDIT21                  1689
#define IDC_CUSTOM1                     1690
#define IDC_CUSTOM2                     1691
#define IDC_STATIC_TEST                 1692
#define IDC_PINGINTERVAL                1693
#define IDC_CONNECTION_LIST             1694
#define IDC_BUTTON_CONNECTION           1696
#define IDC_TABLEDATAPOSITION           1697
#define IDC_CHECK3                      1698
#define IDC_INFOPOSITION                1698
#define IDC_LOAD_FILE                   1698
#define IDC_BUTTON_KEEPBOTH             1698
#define IDC_INFOPOSITION2               1699
#define IDC_HISTORYPOSITION             1699
#define IDC_PINGTEXT                    1699
#define IDC_BUTTON_REPLACE              1699
#define IDC_BUTTON_SKIP                 1700
#define IDC_INITCMDTEXT                 1702
#define IDC_MODEVALUE                   1703
#define IDC_RADIO2                      1704
#define IDC_KEEPALIVESEC                1705
#define IDC_CHECKALL                    1705
#define IDC_STATIC_FILE                 1706
#define IDC_STATUS                      1707
#define IDC_CHECK1                      1708
#define IDC_ISCLEARTEXT                 1708
#define IDC_NEVEROPEN                   1708
#define IDC_SELCHECK                    1708
#define IDC_CH                          1708
#define IDC_PROMPTTRANSACTION           1708
#define IDC_OPENSEL                     1709
#define IDC_PROMPTCLOSETRANSACTION      1710
#define IDC_PROGRESS2                   1712
#define IDC_RESTORE_PROGRESS            1712
#define IDC_CONNECTION_NAME             1713
#define IDC_DOWNLOAD                    1715
#define IDC_INITCOMMANDDETAIL           1749
#define IDC_ROWSIDTEXT                  1750
#define IDC_ZIP                         1750
#define IDC_TIMESTAMP_PREFIX            1751
#define IDC_FILE_TABLE                  1752
#define IDC_ROWSIDBY                    1753
#define IDC_SAVEPOINTEDIT               1755
#define IDC_SAVEPOINTRELEASE_COMBO      1756
#define IDC_ROLLBACKTO_COMBO            1757
#define IDM_VERIFY                      1801
#define IDM_NEXT                        1802
#define IDM_RESEND                      1803
#define IDM_BACK                        1804
#define IDC_LITE                        1805
#define IDC_IMAGELINK                   1806
#define IDC_TRIALEMAIL                  1807
#define IDC_PASSCODE                    1808
#define IDC_TITLE                       1809
#define IDC_TRIALNOTESTATIC             1810
#define IDC_TITLE2                      1811
#define IDC_TRIALSTATIC                 1812
#define IDC_INITCOMMANDHELP             2644
#define IDC_COMBOCUSTOM                 2645
#define IDC_SHOWSQL                     2646
#define IDC_HIDESQL                     2647
#define ID_IMPORT_FROMXML               2655
#define ACCEL_IMPORTXML                 2656
#define FAVORITE_MENU_ID                2900
#define IDC_LINK_PAID                   2901
#define IDI_TABIMG_FIELDS               10000
#define IDI_TABIMG_ADVPROP              10001
#define IDI_TABIMG_INDEXES              10002
#define IDI_TABIMG_FOREIGNKEYS          10003
#define IDI_TABIMG_PREVIEW              10004
#define IDS_TITLE1                      10235
#define IDS_SUBTITLE1                   10236
#define IDS_TITLE2                      10237
#define IDS_SUBTITLE2                   10239
#define IDS_TITLE3                      10241
#define IDS_SUBTITLE3                   10242
#define IDS_TITLE4                      10243
#define IDS_SUBTITLE4                   10244
#define IDS_TITLE5                      10245
#define IDS_SUBTITLE5                   10246
#define IDC_DLGCONNECT_STOREPASSWORD    10247
#define IDC_READONLY                    10289
#define ID_LF_1                         39100
#define ID_LF_2                         39101
#define ID_LF_3                         39102
#define ID_LF_4                         39103
#define ID_LF_5                         39104
#define ID_LF_6                         39105
#define ID_LF_7                         39106
#define ID_LF_8                         39107
#define ID_LF_9                         39108
#define ID_LF_10                        39109
#define IDS_COMMUNITY_AD_1              39501
#define IDS_COMMUNITY_AD_2              39502
#define IDS_COMMUNITY_AD_3              39503
#define IDS_COMMUNITY_AD_4              39504
#define IDS_COMMUNITY_AD_5              39505
#define IDS_COMMUNITY_AD_6              39506
#define IDS_COMMUNITY_AD_7              39507
#define IDS_COMMUNITY_AD_8              39508
#define IDS_COMMUNITY_AD_9              39509
#define IDS_COMMUNITY_AD_10             39510
#define IDS_COMMUNITY_AD_11             39511
#define IDS_COMMUNITY_AD_12             39512
#define IDS_COMMUNITY_AD_13             39513
#define IDS_COMMUNITY_AD_14             39514
#define IDS_COMMUNITY_AD_15             39515
#define IDS_COMMUNITY_AD_16             39516
#define IDS_COMMUNITY_AD_17             39517
#define IDS_COMMUNITY_AD_18             39518
#define IDS_COMMUNITY_AD_19             39519
#define IDS_COMMUNITY_AD_20             39520
#define IDS_COMMUNITY_AD_21             39521
#define IDS_COMMUNITY_AD_22             39522
#define IDS_COMMUNITY_AD_23             39523
#define IDS_COMMUNITY_AD_24             39524
#define IDS_COMMUNITY_AD_25             39525
#define IDS_COMMUNITY_AD_26             39526
#define IDS_COMMUNITY_AD_27             39527
#define IDS_COMMUNITY_AD_28             39528
#define IDS_COMMUNITY_AD_29             39529
#define IDS_COMMUNITY_AD_30             39530
#define IDS_COMMUNITY_AD_31             39531
#define IDS_COMMUNITY_AD_32             39532
#define IDS_COMMUNITY_AD_33             39533
#define IDS_COMMUNITY_AD_34             39534
#define IDS_COMMUNITY_AD_35             39535
#define IDS_COMMUNITY_AD_36             39536
#define IDS_COMMUNITY_AD_37             39537
#define IDS_COMMUNITY_AD_38             39538
#define IDS_COMMUNITY_AD_39             39539
#define IDS_COMMUNITY_AD_40             39540
#define IDS_COMMUNITY_AD_41             39541
#define IDS_COMMUNITY_AD_42             39542
#define IDS_COMMUNITY_AD_43             39543
#define IDS_COMMUNITY_AD_44             39544
#define IDS_COMMUNITY_AD_45             39545
#define IDS_COMMUNITY_AD_46             39546
#define IDS_COMMUNITY_AD_47             39547
#define IDS_COMMUNITY_AD_48             39548
#define IDS_COMMUNITY_AD_49             39549
#define IDS_COMMUNITY_AD_50             39550
#define IDS_COMMUNITY_AD_51             39551
#define IDS_COMMUNITY_AD_52             39552
#define IDS_COMMUNITY_AD_53             39553
#define IDS_COMMUNITY_AD_54             39554
#define IDS_COMMUNITY_AD_55             39555
#define IDS_COMMUNITY_AD_56             39556
#define IDS_COMMUNITY_AD_57             39557
#define IDS_COMMUNITY_AD_58             39558
#define IDS_COMMUNITY_AD_59             39559
#define IDS_COMMUNITY_AD_60             39560
#define IDS_COMMUNITY_AD_61             39561
#define IDS_COMMUNITY_AD_62             39562
#define IDS_COMMUNITY_AD_63             39563
#define IDS_COMMUNITY_AD_64             39564
#define IDS_COMMUNITY_AD_65             39565
#define IDS_COMMUNITY_AD_66             39566
#define IDS_COMMUNITY_AD_67             39567
#define IDS_COMMUNITY_AD_68             39568
#define IDS_COMMUNITY_AD_69             39569
#define IDS_COMMUNITY_AD_70             39570
#define IDS_COMMUNITY_AD_71             39571
#define IDS_COMMUNITY_AD_72             39572
#define IDS_COMMUNITY_AD_73             39573
#define IDS_COMMUNITY_AD_74             39574
#define IDS_COMMUNITY_AD_75             39575
#define IDM_FILE_CONNECT                40000
#define IDS_NAGENT                      40001
#define IDM_FILE_NEWCONNECTION          40002
#define IDM_FILE_CLOSECONNECTION        40003
#define IDM_FILE_CLOASEALL              40004
#define IDM_FILE_SAVESQL                40005
#define IDM_FILE_OPENSQL                40006
#define IDM_FILE_EXIT                   40007
#define IDM_FILE_SAVEAS                 40008
#define IDM_EDIT_CUT                    40011
#define IDM_EDIT_COPY                   40012
#define IDM_EDIT_PASTE                  40013
#define IDM_EDIT_UNDO                   40014
#define IDM_EDIT_ADVANCED_UPPER         40016
#define IDM_EDIT_ADVANCED_LOWER         40017
#define IDM_EDIT_ADVANCED_COMMENT       40018
#define IDM_EDIT_ADVANCED_REMOVE        40019
#define IDM_EDIT_ADDSQL                 40020
#define IDM_WINDOW_CASCADE              40024
#define IDM_WINDOW_TILE                 40025
#define IDM_WINDOWS_ICONARRANGE         40026
#define IDM_HELP_ABOUT                  40027
#define IDM_HELP_SHORT                  40028
#define ACCEL_UPPERCASE                 40029
#define ACCEL_LOWERCASE                 40030
#define ACCEL_COMMENT                   40031
#define ACCEL_REMOVE_COMMENT            40032
#define ID_IMPORTEXPORT_EXPORTTABLES    40046
#define ID_IMEX_TEXTFILE                40047
#define IDM_EDIT_TEMP_SELECTSTMT        40048
#define IDM_EDIT_TEMP_JOINSTMT          40049
#define IDM_EDIT_TEMP_INSERT1           40050
#define IDM_EDIT_TEMP_INSERT2           40051
#define IDM_EDIT_TEMP_UPDATE            40052
#define IDM_EDIT_TEMP_DELETE            40053
#define IDM_EDIT_TEMP_TRUNCATE          40054
#define IDM_EDIT_TEMP_REPLACE           40055
#define IDM_EDIT_TEMP_LOADDATA          40056
#define IDM_EDIT_TEMP_CREATE1           40057
#define IDM_EDIT_TEMP_CREATE2           40058
#define IDM_EDIT_TEMP_DROP1             40059
#define IDM_EDIT_TEMP_DROP2             40060
#define IDM_EDIT_TEMP_ALTER             40061
#define IDM_EDIT_TEMP_RENAME            40062
#define IDM_EDIT_TEMP_USER1             40064
#define IDM_EDIT_TEMP_USER2             40065
#define IDM_EDIT_TEMP_BEGIN             40067
#define IDM_EDIT_TEMP_COMMIT            40068
#define IDM_EDIT_TEMP_ROLLBACK          40069
#define IDM_EDIT_TEMP_LOCK              40070
#define IDM_EDIT_TEMP_UNLOCK            40071
#define IDM_EDIT_TEMP_TRANSACTION       40072
#define IDM_EDIT_TEMP_CREATE3           40073
#define IDM_EDIT_REDO                   40074
#define IDM_EXECUTE                     40077
#define IDM_EDIT_SELECTALL              40079
#define IDM_REFRESHOBJECT               40080
#define ID_OBJECT_DROPDATABASE          40082
#define ID_OBJECT_DROPTABLE             40083
#define ID_OBJECT_INSERTSTMT            40084
#define IDM_EDIT_MANPF                  40086
#define ACCEL_NEWCONN                   40088
#define ACCEL_DISCONN                   40089
#define ACCEL_SAVE                      40091
#define ACCEL_ADDFAVORITE               40093
#define ID_POWERTOOLS_SCHEDULEEXPORT    40094
#define ACCEL_EXECUTE                   40095
#define ACCEL_REFRESH                   40096
#define IDM_HELP_HELP                   40097
#define ACCEL_EXECUTESEL                40098
#define ACCEL_EXECUTEALL                40099
#define ID_TABLE_MAKER                  40101
#define IDM_TMAKER_SETPRIMARY           40103
#define IDM_TMAKER_INSERTCOLUMN         40104
#define IDM_TMAKER_DELETECOLUMN         40105
#define IDM_TMAKER_SAVE                 40107
#define IDM_DATATOCLIPBOARD             40108
#define IDM_SELDATATOCLIPBOARD          40109
#define IDM_TOOLS_TABLEDIAG             40116
#define IDM_EDIT_RESULT_TEXT            40118
#define ACCEL_RESULT                    40119
#define ACCEL_FIRSTTAB                  40120
#define ACCEL_SECONDTAB                 40121
#define ACCEL_THIRDTAB                  40122
#define ACCEL_FOURTHTAB                 40123
#define ACCEL_FIFTHTAB                  40124
#define ACCEL_FOCUSOBJECT               40125
#define ACCEL_FOCUSRESULT               40126
#define ACCEL_FOCUSEDITOR               40127
#define ACCEL_FIND                      40128
#define IDM_EDIT_FIND                   40129
#define IDM_EDIT_REPLACE                40130
#define ACCEL_REPLACE                   40131
#define IDC_EDIT_SHOWOBJECT             40133
#define ACCEL_OBJECT                    40134
#define ACCEL_TMENU                     40135
#define ACCEL_PMENU                     40136
#define ID_TOOLS_FLUSH                  40137
#define ID_EDIT_INSERTTEMPLATES         40139
#define IDM_IMEX_EXPORTDATA             40140
#define IDI_ADDROW                      40140
#define ACCEL_EXPORT                    40141
#define IDM_EDIT_TEMP_BACKUP_RESTORE    40141
#define IDI_DELETEROW                   40141
#define IDM_TEDITOR_SETPRIMARY          40142
#define IDI_MOVEUP                      40142
#define IDM_TEDITOR_DELETECOLUMN        40143
#define IDI_MOVEDOWN                    40143
#define IDM_TEDITOR_INSERTCOLUMN        40144
#define ID_OBJECT_RENAMETABLE           40150
#define ID_OBJECT_VIEWDATA              40151
#define ID_OBJECT_CLEARTABLE            40152
#define ID_OBJECT_ADVANCED              40153
#define ID_OBJECT_DROPFIELD             40155
#define ID_OBJECT_CREATESCHEMA          40156
#define IDM_FILE_NEWSAMECONN            40157
#define ACCEL_NEWSAMECONN               40158
#define ID_OBJECT_SHOWMORE              40160
#define ID_OBJECT_KILLPROCESS           40161
#define ID_OBJECT_COPYTABLE             40162
#define ID_OBJECT_TABLEEDITOR           40165
#define IDM_TOOL_ADDUSER                40166
#define IDM_TOOL_EDITUSER               40167
#define ACCEL_ADDUSER                   40168
#define ACCEL_EDITUSER                  40169
#define ID_OBJECT_INSERTUPDATE          40170
#define ID_QUERYINFO_DELETEALL          40173
#define ID_QUERYINFO_COPY               40174
#define ACCEL_SIXTHTAB                  40175
#define ACCEL_SEVENTHTAB                40176
#define ACCEL_EIGHTHTAB                 40177
#define ACCEL_NINTHTAB                  40178
#define IDM_CREATEDATABASE              40180
#define ACCEL_CREATEDB                  40182
#define ID_OBJECT_CHANGETABLETYPE_ISAM  40184
#define ID_OBJECT_CHANGETABLETYPE_MYISAM 40185
#define ID_OBJECT_CHANGETABLETYPE_HEAP  40186
#define ID_OBJECT_CHANGETABLETYPE_MERGE 40187
#define ID_OBJECT_CHANGETABLETYPE_INNODB 40188
#define ID_OBJECT_CHANGETABLETYPE_BDB   40189
#define ID_OBJECT_CHANGETABLETYPE_GEMINI 40190
#define ID_OBJECT_MANINDEX              40191
#define ID_TOOLS_MANPERM                40192
#define ACCEL_MANUSER                   40194
#define ACCEL_EXPORTBATCH               40195
#define ID_EXPORT_AS                    40196
#define ID_IMPORT_FROMCSV               40197
#define ID_OBJECT_BACKUPDATABASE        40198
#define ID_OBJECT_RESTOREDATABASE       40199
#define IDC_EDIT_SHOWRESULT             40200
#define ACCEL_RESULTWINDOW              40201
#define ID_PF_1                         40201
#define ID_PF_2                         40202
#define ACCEL_IMPORTBATCH               40203
#define ID_PF_3                         40203
#define ID_PF_4                         40204
#define ID_PF_5                         40205
#define ID_COLUMNS_DROPINDEX            40206
#define ACCEL_TABLEDIAG                 40207
#define ACCEL_SCHEMA                    40208
#define ACCEL_EXPORTCSV                 40209
#define ACCEL_IMPORTCSV                 40210
#define ACCEL_MANINDEX                  40212
#define ID_IMPORTEXPORT_DBEXPORTTABLES  40214
#define ID_IMPORTEXPORT_TABLESEXPORTTABLES 40215
#define ID_OBJECT_MAINMANINDEX          40220
#define ACCEL_FLUSH                     40222
#define ACCEL_REORDER                   40224
#define ID_OBJECT_REORDER               40225
#define IDM_TOOL_ADDUSERTIP             40227
#define ID_TOOLS_FLUSHTIP               40228
#define IDM_TOOLS_TABLEDIAGTIP          40229
#define ID_OPEN_COPYDATABASE            40230
#define ID_OBJECT_EMPTYDATABASE         40231
#define IDC_EDIT_SHOWEDIT               40232
#define ACCEL_EDITWINDOW                40233
#define ACCEL_QUERYUPDATE               40234
#define ACCEL_MANREL                    40237
#define ID_SHOW_VARIABLES               40239
#define ID_IMPORTEXPORT_DBEXPORTTABLESTIP 40240
#define ID_IMEX_TEXTFILETIP             40241
#define IDM_TABLE_RELATION              40242
#define ID_OBJECT_CREATESCHEMATIP       40242
#define ID_OBJECT_INSERTUPDATETIP       40243
#define ID_OBJECT_TABLEEDITORTIP        40244
#define ACCEL_INSERTUPDATE              40244
#define ID_OBJECT_MAINMANINDEXTIP       40245
#define ID_OBJECT_TRUNCATEDATABASE      40245
#define IDM_TABLE_RELATIONTIP           40246
#define ID_EXPORT_ASHTML                40248
#define ACCEL_EXPORTXML                 40249
#define ACCEL_EXPORTHTML                40250
#define ACCEL_SETFONT                   40252
#define ID_EXPORT_ASXML                 40254
#define ID_SHOW_PROCESSLIST             40256
#define ID_SHOW_STATUS                  40257
#define IDS_DSYNCTITLE1                 40259
#define IDS_DSYNCSUBTITLE1              40260
#define IDS_DSYNCTITLE2                 40261
#define IDS_DSYNCSUBTITLE2              40262
#define IDS_DSYNCTITLE3                 40263
#define IDS_DSYNCSUBTITLE3              40264
#define IDC_PREF                        40266
#define IDS_DSYNCTITLE4                 40267
#define IDS_DSYNCSUBTITLE4              40268
#define IDS_NOTIFYTITLE1                40269
#define ID_OPEN_COPYTABLE               40270
#define IDS_NOTIFYTITLE2                40271
#define IDS_NOTIFYSUBTITLE2             40272
#define IDS_NOTIFYTITLE3                40273
#define IDS_NOTIFYSUBTITLE3             40274
#define IDS_NOTIFYTITLE4                40275
#define IDS_NOTIFYSUBTITLE4             40276
#define IDS_NOTIFYTITLE5                40277
#define IDS_NOTIFYSUBTITLE5             40278
#define IDS_SCHDSERVERTITLE             40279
#define IDS_SCHDSERVERSUBTITLE          40280
#define IDS_SCHDSELTABLESTITLE          40281
#define IDS_SCHDSELTABLESSUBTITLE       40282
#define IDS_SCHDSELSCRIPTTITLE          40283
#define IDS_SCHDSELSCRIPTSUBTITLE       40284
#define IDS_SCHDOPT1TITLE               40285
#define IDS_SCHDOPT1SUBTITLE            40286
#define IDS_SCHDOPT2TITLE               40287
#define IDS_SCHDOPT2SUBTITLE            40288
#define IDS_SCHDMAILTITLE               40289
#define IDS_SCHDMAILSUBTITLE            40290
#define IDS_SCHDABORTTITLE              40291
#define IDS_SCHDABORTSUBTITLE           40292
#define IDS_SCHDMAILSUBJTITLE           40293
#define ID_STOPQUERY                    40296
#define IDM_IMEX_EXPORTCELL             40298
#define ID_RESULT_INSERT                40300
#define ID_RESULT_DELETE                40302
#define ID_RESULT_CANCEL                40304
#define ACCEL_SETNULL                   40305
#define ID_RESULT_SAVE                  40307
#define IDS_SCHDODBCTITLEDSN            40308
#define IDS_SCHDODBCSUBTITLEDSN         40309
#define IDC_SETEMPTY                    40310
#define IDS_SCHDODBCTITLETYPE           40310
#define IDS_SCHDODBCSUBTITLETYPE        40311
#define ID_IMPORTEXPORT_DBEXPORTTABLES2 40312
#define ID_IMEX_TEXTFILE2               40313
#define IDS_SCHDODBCSUBTITLECREATEQUERY 40315
#define IDS_SCHDODBCTITLEDB             40316
#define IDS_SCHDODBCSUBTITLEDB          40317
#define IDS_SCHDODBCTITLEONERROR        40318
#define IDS_SCHDODBCSUBTITLEONERROR     40319
#define ID_OBJECT_ALTERSTOREDPROCEDURE  40320
#define ID_OBJECT_DROPSTOREDPROCEDURE   40321
#define IDS_SCHDODBCTITLESUBMAIL        40322
#define ID_OBJECT_ALTERFUNCTION         40323
#define ID_OBJECT_DROPFUNCTION          40324
#define ID_OBJECT_DROPTRIGGER           40328
#define ID_OBJECT_ALTERVIEW             40330
#define ID_OBJECT_DROPVIEW              40331
#define ID_OBJECT_CREATEVIEW            40332
#define ID_OBJECT_CREATESTOREDPROCEDURE 40333
#define ID_OBJECT_CREATEFUNCTION        40334
#define ID_OBJECT_CREATETRIGGER         40335
#define ID_OBJECT_ALTERTRIGGER          40336
#define IDS_SCHDODBCTITLECONCLUDE       40337
#define ID_NEW_EDITOR                   40338
#define IDS_NOTIFICATIONCONCLUDE        40339
#define ID_OBJECTS_RENAMEVIEW           40340
#define ID_OBJECTS_RENAMETRIGGER        40342
#define IDM_EDIT_GOTO                   40344
#define ACCEL_GOTO                      40345
#define ACCEL_NEWEDITOR                 40347
#define ACCEL_QUERYBUILDER              40348
#define ID_OBJECT_SELECTSTMT            40352
#define ACCEL_INSERT                    40353
#define ACCEL_SELECT                    40354
#define ID_ADDTOFAVORITES               40359
#define ID_ORGANIZEFAVORITES            40360
#define IDC_SETDEF                      40366
#define IDC_FAVORITENAME                40369
#define IDC_ADDFAVORTREE                40370
#define IDC_NEWFOLDER                   40371
#define IDC_FOLDERNAME                  40372
#define IDC_RENAME                      40373
#define ID_TABDELETE                    40373
#define IDC_MOVETO                      40374
#define ID_REFRESHFAVORITES             40374
#define IDC_ORGTREE                     40376
#define ID_Menu40376                    40376
#define IDC_MOVETREE                    40377
#define ID_EXPORT_EXPORTTABLEDATA       40377
#define ID_FILTER_FIELD_EQUALS          40379
#define ID_OBJECT_EXPORTVIEW            40380
#define ID_COLUMNS_MANAGECOLUMNS        40381
#define ID_GRIDMENU_INSERTCOLUMN        40382
#define ID_INDEXES_CREATEINDEX          40382
#define ID_GRIDMENU_DELETECOLUMN        40383
#define ID_INDEXES_EDITINDEX            40383
#define IDS_STRING40384                 40384
#define ID_DELETE_LINE                  40384
#define ID_INDEXES_DROPINDEX            40384
#define ID_OPEN_COPY                    40385
#define ID_SCHEMADESIGNER               40387
#define ID_GRIDMENU_CLEARALL            40392
#define ID_FILTER_FIELD_GREATERTHEN     40392
#define ACCEL_SCHEMADESIGNER            40392
#define ID_CONTEXT_COPYQUERYTOCLIPBOARD 40393
#define ID_FILTER_FIELD_LESSTHEN        40393
#define ID_CONTEXT_COPYQUERYTONEWQUERYTAB 40394
#define ID_QUERYBUILDER                 40395
#define ID_FILTER_FIELD_NOTEQUALS       40396
#define ID_FILTER_FIELDLIKEBEGIN        40397
#define ID_FILTER_FIELDLIKEEND          40398
#define IDS_SCHDODBCTITLESELECTTABLE    40412
#define IDS_SCHDODBCSUBTITLESELECTTABLE 40413
#define IDS_SCHDODBCTITLECREATEQUERY    40414
#define IDS_SCHDODBCTITLEMAILINFO       40420
#define IDS_SCHDODBCSUBTITLEMAILINFO    40421
#define IDS_SCHDODBCSUBTITLESUBMAIL     40423
#define IDS_SCHDODBCTITLESCHEDULE       40424
#define IDM_EDIT_TEMP_CREATEPROCEDURE   40425
#define IDM_EDIT_TEMP_CREATEFUNCTION    40426
#define IDM_EDIT_TEMP_ALTERPROCEDURE    40427
#define IDM_EDIT_TEMP_ALTERFUNCTION     40428
#define IDM_EDIT_TEMP_DROPPROCEDURE     40429
#define IDM_EDIT_TEMP_DROPFUNCTION      40431
#define IDM_EDIT_TEMP_CREATEVIEW        40432
#define IDM_EDIT_TEMP_ALTERVIEW         40433
#define IDM_EDIT_TEMP_DROPVIEW          40434
#define IDM_EDIT_TEMP_CREATETRIGGER     40435
#define IDM_EDIT_TEMP_DROPTRIGGER       40436
#define IDM_EDIT_TEMP_CREATEEVENT       40437
#define IDS_SCHDEXPORTCONCLUDETITLE     40438
#define IDS_DATABASESYNCCONCLUDE        40440
#define IDS_NOTIFYSUBTITLE1             40470
#define IDM_DATASYNC                    41501
#define ACCEL_DATASYNC                  41502
#define IDC_DIFFTOOL                    41503
#define ACCEL_DIFFTOOL                  41504
#define ID_TOOLS_ODBCIMPORT             41505
#define ACCEL_ODBC                      41506
#define IDC_TOOLS_NOTIFY                41507
#define ACCEL_NOTIFY                    41508
#define ID_POWERTOOLS_SCHEDULEEXPORT2   41509
#define ACCEL_SCHDEXPORT                41510
#define IDC_SSLGRP                      41510
#define IDM_TOOL_JOBMAN                 41511
#define ID_REBUILDTAGS                  41512
#define IDC_SSLHELP                     41512
#define ID_EDIT_LISTALLTAGS             41513
#define IDC_SSLCLIENTKEY                41513
#define ID_EDIT_LISTMATCHINGTAGS        41514
#define IDC_CLIENTKEY                   41514
#define IDC_SSLCLIENTCER                41515
#define IDC_CLIENTCER                   41516
#define IDC_SSLCACER                    41517
#define IDC_CACER                       41518
#define IDC_SSLCIPHER                   41519
#define IDC_CIPHER                      41520
#define IDC_SSLKEYFILE                  41521
#define IDC_SSLCAFILE                   41523
#define IDC_SSLCERFILE                  41524
#define IDC_SSLAUTH                     41525
#define IDC_SSHPASSWORDRADIO            41542
#define IDC_SSHPRIVATERADIO             41543
#define IDC_SSHPRIVATEKEYTITLE          41544
#define IDC_SSHPRIVATEKEY               41545
#define IDC_SSHSAVEPHRASE               41548
#define IDC_SSHPRIVATEKEYFILE           41549
#define IDC_SSHPASSGRP                  41556
#define IDC_SSLAUTHGRP                  41557
#define ACCEL_EXECUTE_MENU              41568
#define ACCEL_EXECUTESEL_CTRL_F9        41572
#define ACCEL_EXECUTEALL_SHIFT_F9       41573
#define ACCEL_EXECUTESEL_CTRL_F5        41574
#define ACCEL_EXECUTEALL_SHIFT_F5       41575
#define IDC_BUY_LINK                    41576
#define IDM_ALTERDATABASE               41579
#define ID_OBJECT_CREATEEVENT           41582
#define IDM_EDIT_TEMP_ALTEREVENT        41583
#define IDM_EDIT_TEMP_DROPEVENT         41584
#define ID_OBJECT_ALTEREVENT            41587
#define ID_OBJECT_DROPEVENT             41588
#define ID_OBJECT_RENAMEEVENT           41591
#define ID_OPEN_SAVEHISTORY             41602
#define ID_OBJECT_UPDATESTMT            41608
#define ID_OBJECT_DELETESTMT            41610
#define ACCEL_UPDATE                    41611
#define IDS_DSYNCTYPETITLE              41611
#define ACCEL_DELETE                    41612
#define IDS_DSYNCTYPESUBTITLE           41612
#define IDM_EDIT_TEMP_ALTERDB           41613
#define IDM_HELP_CHKUPGRD               41615
#define ID_CONTEXT_COPYQUERYTOSAMEQUERY 41618
#define ACCEL_CLOSETAB                  41619
#define ACCEL_NAVIGATETABUP             41620
#define ACCEL_NAVIGATETABDOWN           41621
#define ID_FILE_CLOSETAB                41623
#define ID_EDIT_SWITCHTABSTOLEFT        41626
#define ID_EDIT_SWITCHTABSTORIGHT       41627
#define ACCEL_FINDNEXT                  41628
#define ACCEL_FORMATSELECTEDQUERY       41640
#define ACCEL_FORMATALLQUERIES          41641
#define ACCEL_FORMATCURRENTQUERY        41642
#define IDC_TABCOLLIST                  41649
#define IDC_TABCOLLISTLINE              41650
#define IDC_LINEBRK                     41651
#define ID_CONTEXT_CREATEVIEWFROMQB     41652
#define IDM_FILE_OPENSQLNEW             41655
#define ACCEL_OPENNEW                   41656
#define IDC_SHOWPREVIEW                 41658
#define ID_IMPORT_EXTERNAL_DATA         41659
#define ID_DB_TABLE_MAKER               41660
#define ID_DB_CREATEVIEW                41661
#define ID_DB_CREATESTOREDPROCEDURE     41662
#define ID_DB_CREATEFUNCTION            41663
#define ID_DB_CREATETRIGGER             41664
#define ID_DB_CREATEEVENT               41665
#define ACCEL_QUERYUPDATE_KEY           41666
#define ID_HELP_REGISTRATION            41668
#define IDM_TOOL_RENAMEUSER             41670
#define IDM_OBCOLOR                     41671
#define ID_DB_DATASEARCH                41675
#define ID_EDIT_INSERTFILE              41678
#define ID_DATASEARCH                   41679
#define IDM_DUPLICATE_ROW               41681
#define ACCEL_FIRSTCONN                 41682
#define ACCEL_SECONDCONN                41683
#define ACCEL_THIRDCONN                 41684
#define ACCEL_FOURTHCONN                41685
#define ACCEL_FIFTHCONN                 41686
#define ACCEL_SIXTHCONN                 41687
#define ACCEL_SEVENTHCONN               41688
#define ACCEL_EIGTHCONN                 41689
#define ACCEL_NINTHCONN                 41690
#define ID_DISCONNECT                   41691
#define IDM_EDIT_FINDNEXT               41697
#define ID_FILTER_CUSTOMFILTER          41698
#define ACCEL_CLOSECONNECTION           41698
#define ID_EDIT_SWITCHTABSTOLEF         41698
#define ID_TOOLS_USERMANAGER            41699
#define ID_RESETFILTER                  41701
#define ID_INFOTAB                      41703
#define ID_HISTORY                      41704
#define ID_FILTER_FIELDLIKEBOTH         41705
#define ID_VIEW_GRIDVIEW                41706
#define ID_VIEW_FORMVIEW                41707
#define ID_VIEW_TEXTVIEW                41708
#define ID_TOOLS_CHANGELANGUAGE         41710
#define ACCEL_CHANGELANGUAGE            41711
#define ACCEL_GRIDFORM                  41712
#define ID_EDIT_CHANGEBACKGROUNDCOLOR   41715
#define ID_TABMENU                      41716
#define ID_TABMENU1                     41717
#define ID_NEWQUERYEDITOR_NEWQUERYEDITOR 41718
#define ID_NEWQUERYEDITOR_S             41719
#define ID_NEWQUERYEDITOR_SSSS          41720
#define ID_TABMENU41721                 41721
#define ID_CONNTABPLUSMENU_SS           41722
#define ID_CONNTABPLUSMENU_DD           41723
#define ACCEL_DATASEARCH                41726
#define ID_OBJECT_COPY                  41727
#define ID_OBJECT_SELECTALL             41728
#define ID_OBJECT_FIND                  41729
#define ID_OBJECT_FINDNEXT              41730
#define ID_TABLE_OPENINNEWTAB           41732
#define ACCEL_CHANGEVIEW                41735
#define ACCEL_OPENTABLESTICKY           41736
#define IDM_COPYNORMALIZED              41737
#define ACCEL_FOCUSDATASEARCH           41738
#define ID_EDIT_LISTFUNCTIONANDROUTINEPARAMETERS 41742
#define ID_TABMENU_HISTORYTAB           41743
#define ID_OPEN_FIND                    41743
#define ID_HISTORYTAB                   41744
#define ID_OPEN_FINDNEXT                41744
#define ID_TOOLS_HISTORY                41745
#define ID_OPEN_SELECTALL               41745
#define ID_TOOLS_OBJECTINFO             41746
#define ID_QUERYINFO_SELECTALL          41746
#define ACCEL_HISTORYTAB                41747
#define ID_QUERYINFO_SAVEHISTORY        41747
#define ACCEL_INFOTAB                   41748
#define ID_QUERYINFO_FIND               41748
#define ID_QUERYINFO_FINDNEXT           41749
#define ID_TRANSACTION_SETAUTOCOMMIT    41751
#define ID_TRANSACTION_TRX              41752
#define ID_TRANSACTION_STARTTRANSACTION 41753
#define ID_OPEN_SELECT                  41754
#define ID_OPEN_COPYALL                 41755
#define ID_OPEN_SELECTALL41756          41756
#define ID_DATABASE_REBUILDTAGS         41756
#define ID_TABMENU_CREATETABLE          41757
#define ID_TABMENU_HISTORY              41758
#define ID_TABMENU_INFO                 41759
#define ID_OBJECT_COPYALL               41763
#define ID_TABMENU_TABLEDATA            41768
#define ID_CONNECTIONTAB_CHANGEOBJECTBROWSERCOLOR 41769
#define ID_EXPORT_EXPORTCONNECTIONDETAILS 41770
#define ID_EXPORT_IMPORTCONNECTIONDETAILS 41771
#define ACCEL_NOFORMATCOPY              41775
#define ID_MENU_SHOWONLYERRORS          41776
#define ACCEL_ALTERTABLE                41777
#define ACCEL_OBFILTER                  41778
#define ID_EXPLAIN_EXPLAIN              41784
#define ID_EXPLAIN_EXTENDED             41789
#define ID_EDIT_EXPLAIN                 41791
#define ID_VDDTOOL                      41793
#define ACCEL_VDDTOOL                   41796
#define ID_TRX_REPEATABLEREAD           41797
#define ID_TRX_READCOMMITED             41798
#define ID_TRX_READUNCOMMITED           41799
#define ID_TRX_SERIALIZABLE             41800
#define ID_STARTTRANSACTION_WITHNOMODIFIER 41801
#define ID_STARTTRANSACTION_WITHCONSISTENTSNAPSHOT 41802
#define ID_WITHCONSISTENTSNAPSHOT_READONLY 41803
#define ID_WITHCONSISTENTSNAPSHOT_READWRITE 41804
#define ID_STARTTRANSACTION_READONLY    41805
#define ID_STARTTRANSACTION_READWRITE   41806
#define ID_TRANSACTIONS_COMMIT          41807
#define ID_COMMIT_WITHNOMODIFIER        41808
#define ID_COMMIT_ANDCHAIN              41809
#define ID_COMMIT_ANDNOCHAIN            41810
#define ID_COMMIT_RELEASE               41811
#define ID_COMMIT_NORELEASE             41812
#define ID_TRANSACTIONS_ROLLBACK        41813
#define ID_ROLLBACK_TOSAVEPOINT         41814
#define ID_ROLLBACK_TRANSACTION         41815
#define ID_ROLLBACK_ANDCHAIN            41816
#define ID_ROLLBACK_ANDNOCHAIN          41817
#define ID_ROLLBACK_RELEASE             41818
#define ID_ROLLBACK_NORELEASE           41819
#define ID_TRANSACTIONS_SAVEPOINT       41820
#define ID_SAVEPOINT_CREATESAVEPOINT    41821
#define ID_SAVEPOINT_RELEASESAVEPOINT   41822
#define ID_Menu                         41823
#define ID_Menu41826                    41826
#define ID_Menu41827                    41827
#define IDM_COLLAPSEOBJECT              41828
#define IDC_INITCOMMAND                 44114
#define IDC_EDITINITCOMMAND             44115
#define IDC_INVISIBLE                   44116
#define IDR_SAVEPROFILERMENU            44117
#define ID_OPEN_SAVEPROFILER            44118
#define IDR_TABMENU2                    44119
#define ID_FILE_RENAMETAB               44120
#define IDR_TABMENU3                    44121
#define IDD_RENAMETAB                   44122
#define IDC_RENAMETAB                   44123
#define ACCEL_RENAMEQUERYTAB            44124
#define IDI_RENAMEQUERY_16              44125
#define ID_SAVESESSION                  44126
#define ID_OPENSESSION                  44127
#define ID_SAVESESSIONAS                44128
#define ID_CLOSESESSION                 44129
#define IDI_SAVESESSION_16              44130
#define IDI_OPENSESSION_16              44131
#define IDI_CLOSESESSION_16             44132
#define ACCEL_OPENSESSION               44133
#define ACCEL_SAVESESSION               44134
#define ACCEL_ENDSESSION                44135
#define ACCEL_CREATETABLE               44136
#define ID_UNSORT                       44137
#define IDD_CREATESAVEPOINT             44140
#define IDD_RELEASESAVEPOINT            44141
#define IDD_ROLLBACKTO                  44142
#define IDI_CHECKCONSTRAINT             44143
#define IDC_PLUGIN_PROMPT				44144
#define IDC_AUTHPLUGIN					44145


// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        1018
#define _APS_NEXT_COMMAND_VALUE         41829
#define _APS_NEXT_CONTROL_VALUE         1716
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
