#define IDR_COPYRESULTMENU              400
#define IDC_TOOLBAR                     1000
#define IDC_TOOLCOMBO                   1001
#define IDC_FRAMESTATUS                 1002
#define IDC_TOOLBAR2                    1003
#define IDC_EDITCHECK                   1004
#define IDC_OBJECTTREE                  1009
#define IDC_QUERYEDIT                   1010
#define IDC_QUERYTAB                    1011
#define IDC_CONNECTIONTAB               1012
#define IDC_QUERYSTATUS                 1013
#define IDC_VSPLITTER                   1014
#define IDC_QUERYMESSAGEEDIT            1016
#define IDC_QUERYRESULTEDIT             1017
#define IDC_ADVPROPLIST                 1118
#define IDC_HISTORY		                1119
#define IDC_ONUPDATECASCADE             1268
#define IDC_CONFIRMONSDCLOSE            1451
#define IDC_COMMTITLE                   1489
#define IDC_QUERYRIBBON                 1490
#define IDC_PREVIEWGROUP                1508
#define IDC_PQAADVISOR                  1511
#define IDC_INFOFORMATTEXT              1516
#define IDC_INFOHTMLMODE                1518
#define IDC_INFOTEXTMODE                1519
#define IDC_REFRESHINFOTAB              1521
#define IDC_TIMEOUTDEF1                 1530
#define IDC_TIMEOUTOPT1                 1531
#define IDC_TIMEOUTEDIT1                1532
#define IDM_TMAKER_CLOSE                40106
#define ACCEL_PASTE                     40110
#define ACEL_EMPTYTABLE                 40163
#define ACCEL_COPYTABLE                 40164
#define ACCEL_KEYSHORT                  40221
#define ID_EXPORT_EXPORTTABLEDATA       40377
#define ID_COLUMNS_MANAGECOLUMNS        40381
#define ID_INDEXES_CREATEINDEX          40382
#define ID_INDEXES_EDITINDEX            40383
#define ID_INDEXES_DROPINDEX            40384
#define ID_SCHEMA_ADDTABLES             40390
#define ID_SCHEMA_NEWTABLE              40391
#define ID_SCHEMA_REFRESHCANVAS         40416
#define ID_SCHEMA_LOADCANVAS            40433
#define ID_QB_QUERYTOCLIPBOARD          41559
#define ID_QB_QUERYTONEWEDITOR          41560
#define ID_QB_QUERYTOSAMEEDITOR         41561
#define ID_SD_ALTERTABLE                41568
#define IDM_DB_REFRESHOBJECT            41569
#define ID_SD_MANAGE_INDEX              41569
#define ID_SD_MANAGE_RELATIONSHIP       41570
#define ID_SD_TABLEVIEW                 41571
#define ID_SCHEMA_SAVEASBMP             41578
#define ID_SD_PRINTCANVAS               41600
#define IDC_TOOLBAR                     1000
#define IDC_TOOLCOMBO                   1001
#define IDC_TOOLBAR2                    1003
#define IDC_QUERYEDIT                   1010
#define IDC_QUERYTAB                    1011
#define IDC_TABLETAB                    2022
#define IDC_CONNECTIONTAB               1012
#define IDC_LIMIT1                      1041
#define IDC_LIMITLOW                    1042
#define IDC_LIMIT2                      1042
#define IDC_CHK_DROPTABLE               1084
#define IDC_CHK_DROPVIEWS               1099
#define IDC_CHK_DROPOBJECTS             1099
#define IDC_CHK_DROPPROCEDURES          1100
#define IDC_CHK_DROPFUNCTIONS           1101
#define IDC_CHK_DROPTRIGGERS            1102
#define IDC_OBJECTFILTER                1103
#define IDC_ABORT                       1211

#define IDC_AVGROWLEN                   2003
#define IDC_MAXROWS                     2004
#define IDC_TABLETYPESLIST              2005                  
/*
#define IDC_COMMENT                     2001
#define IDC_AUTOINCR                    2002
#define IDC_AVGROWLEN                   2003
#define IDC_MAXROWS                     2004
#define IDC_MINROWS                     2005
#define IDC_CHUNKS                      2006
#define IDC_CHUNKSIZE                   2007
*/
#define IDC_GROUP1                      1214
#define IDC_FRAME                       1243
#define IDC_SINSHEET                    1373
#define IDYESTOALL                      1376
#define IDC_INSERTUPDATE                1384
#define IDC_NEXT                        1464
#define IDC_PREVIOUS                    1465
#define IDC_CHK_DROPEVENTS              1466
#define IDNOTOALL                       1553
#define IDC_ICONBOX                     1554
#define IDM_SEPARATOR                   40075
#define ID_EXPORT_EXPORTTABLEDATA       40377
#define IDC_ROW_MSG                     40382
#define IDC_WARN_MSG                    40386
#define ID_SDLF_1                       40441
#define IDM_FLIPGRID                    41567
#define IDM_DB_REFRESHOBJECT            41569
#define ID_SD_PRINTCANVAS               41600
#define ID_SDZOOMIN                     41605
#define ID_SDZOOMOUT                    41606
#define IDC_TABLEDATAEDIT               41622
#define IDC_SHOWDBTABLE                 41630
#define ID_FORMATCURRENTQUERY           41653
#define IDC_ROWSINRANGE                 41657
#define ID_DISCONNECT                   41691
#define IDM_FORM_GRID_VIEWS             41702
#define IDC_FORHOST                     1055
#define IDC_FORHOSTST                   1328
#define IDC_COMMTITLE                   1489
#define IDM_SEPARATOR                   40075
#define IDC_MYSQLDEFSRVST               40378
#define ID_COLUMNS_MANAGECOLUMNS        40381
#define ID_TEST_TEST3                   40383
#define ID_DELETE_LINE                  40384
#define ID_FORMATCURRENTQUERY           41653
#define IDC_HSPLITTER                   1015
#define IDC_TRIALTEXT					51653
#define IDC_TRIALBUY					51654
